title: HEX Generator
name: xrayhexgenerator
version: 2.2.1+26
summary: HEX Generator
description: A simple yet versatile HEX Generator application
contact: xrayadamo@gmail.com
icon: snap/gui/xrayhexgenerator.png
confinement: strict
base: core24
grade: stable
license: MIT
source-code: https://github.com/rayadams/xrayhexgenerator-rs
website: https://www.rayadams.app
issues: https://github.com/rayadams/xrayhexgenerator-rs/issues

platforms:
  amd64:
  arm64:
   
apps:
  xrayhexgenerator:
    command: bin/xrayhexgenerator
    extensions: [gnome]
    common-id: app.rayadams.xrayhexgenerator
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11

parts:
  xrayhexgenerator:
    plugin: rust
    source: .
    rust-channel: stable
    build-packages:
      - pkg-config
      - libgtk-4-dev
      - libadwaita-1-dev

  assets:
    plugin: dump
    source: assets
    organize:
      '*': assets/
